#!/bin/sh

if [ "`uname -m`" = "x86_64" ]; then
	ver="linux-x64"
else
	ver="linux-x86"
fi

path=/opt/farm/ext/db-utils/support/postgresql-10.7-1/$ver
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$path/lib  "$path/bin/pg_dump" "$@"
